name: Verify, Build, & Deploy

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Cache Node Modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: node_modules/
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      # Any way to encapsulate all of this with cache-hit?
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Install Packages
        run: npm ci

  verify:
    name: Verify
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Cache Node Modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: node_modules/
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Linting
        run: npm run lint
      - name: Coverage
        run: npm run test:coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - name: Cache Node Modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: node_modules/
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Cache NextJS
        id: cache-nextjs
        uses: actions/cache@v3
        with:
          path:  |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Build
        run: npm run build

  deploy-docker:
    name: Deploy (Docker Hub)
    runs-on: ubuntu-latest
    needs: [verify, build]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - name: Cache Node Modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: node_modules/
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Cache NextJS
        id: cache-nextjs
        uses: actions/cache@v3
        with:
          path:  |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: rainbowcafe/silvy
          tags: |
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: rainbowcafe/silvy
          provider: dockerhub
          readme_file: 'README.md'

  deploy-live:
    name: Deploy (Vercel)
    runs-on: ubuntu-latest
    needs: [verify, build]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - name: Cache Node Modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: node_modules/
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Cache NextJS
        id: cache-nextjs
        uses: actions/cache@v3
        with:
          path:  |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - run: npx vercel pull --environment=production --yes --token=${VERCEL_TOKEN}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      - run: npx vercel build --prod
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      - uses: amondnet/vercel-action@v20
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          scope: rainbow-cafe
          vercel-args: '--prod --prebuilt'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          alias-domains: silvy.rains.cafe
